import type { Metadata } from "next";

import localFont from "next/font/local";

import ReactQueryProvider from "./api/ReactQueryProvider";
import AppHeader from "./components/AppHeader";
import "./globals.css";
import "./basic-components.css";
import { fetchShoppingList, fetchWeather } from "./api/data-access";
import { cx } from "./utils";
import { getTasks } from "../pages/api/db";

export const metadata: Metadata = {
  title: "Cadence - Recurring Reminders",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`
const chineseFont = localFont({
  src: "./STKaiti.ttf",
  display: "swap",
  variable: "--chinese-font-source",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
  const shoppingList = await fetchShoppingList();
  const tasks = await getTasks();
  const weather = await fetchWeather();

  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Cadence" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
      </head>
      <body className={cx(chineseFont.variable)}>
        <ReactQueryProvider>
          <AppHeader
            initialShoppingList={shoppingList}
            initialTasks={tasks}
            initialWeather={weather}
          />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
