import type { Metadata } from "next";
import ReactQueryProvider from "./api/ReactQueryProvider";
import AppHeader from "./components/AppHeader";
import "./globals.css";
import "./basic-components.css";
import { fetchShoppingList } from "./api/data-access";

export const metadata: Metadata = {
  title: "Cadence - Recurring Reminders",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
  const shoppingList = await fetchShoppingList();
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AppHeader initialShoppingList={shoppingList} />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
